### PR TITLE
Add nullable=True to User model

### PR DESCRIPTION
**Pull request by gabrielhicks**
Added a nullable=True to users table in password column.

### CODE REVIEW

**Review by DiptoChakrabarty — COMMENTED** [review]
@gabrielhicks  this just part of what I wanted , if you use this code the github oauth  login would not perform successfully.

Once user logins in using github we are retrieving the username and storing that at database , but since there is no password parameter (NULL) it would violate the database rules so I also need a method to generate sample passwords for users using oauth , then we can add nullable as false in the database password .

**Comment by DiptoChakrabarty** [comment]
Currently adding nullable as False would restrict oauth logins so for now I have removed it from database rules but that would mean to tell users to enter no password and that is a bug

**Comment by gabrielhicks** [comment]
Thank you, I will look at it again, if anyone else is interested in working on this in the meantime please allow them to do that!

**Comment by gabrielhicks** [comment]
I attempted again, I am unsure if I am on the right path

**Comment by gabrielhicks** [comment]
Going to make this a method instead.

**Comment by gabrielhicks** [comment]
Im not confident, but I feel this is a better approach. I first created an instance method, but I think that would not work, so I made it a class method and hope that can work. Thank you for letting me give it a shot!

**Comment by gabrielhicks** [comment]
Im going to look back at the code and find where the oauth user is being created. Im re-reading your comments and thinking maybe that is where I should go to fix the missing parameter.

**Comment by gabrielhicks** [comment]
I moved the generate password method into the github_login file, passed a generated password as params into each instantiation of a new user, and set the nullable=True in the Users table. I think this should work and I feel more confident in this solution. 
@DiptoChakrabarty

**Comment by DiptoChakrabarty** [comment]
Hey this looks good can you please send the PR to the development branch from where I will merge to master . This is the flow I am following actually .

**Pull request closed without merging**
